server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ipay-service
          uri: http://localhost:8081
          predicates:
            - Path=/ipay/**
        - id: ibanking-service
          uri: http://localhost:8082
          predicates:
            - Path=/ibanking/**

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: yourSecretKeyHereMustBeVeryLongAndSecure
  expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: DEBUG


# server:
#   port: 8080

# spring:
#   application:
#     name: api-gateway
#   cloud:
#     gateway:
#       routes:
#         - id: ipay-service
#           uri: http://localhost:8081
#           predicates:
#             - Path=/ipay/**
#         - id: ibanking-service
#           uri: http://localhost:8082
#           predicates:
#             - Path=/ibanking/**

#   data:
#     redis:
#       host: localhost
#       port: 6379

# jwt:
#   secret: yourSecretKeyHereMustBeVeryLongAndSecure
#   expiration: 86400000  # 24 hours in milliseconds

# logging:
#   level:
#     org.springframework.cloud.gateway: DEBUG
#     org.springframework.security: DEBUG

# # Configuration pour SpringDoc OpenAPI
# springdoc:
#   swagger-ui:
#     path: /swagger-ui.html
#     enabled: true
#   api-docs:
#     path: /v3/api-docs
#     enabled: true